server:
  port: 1234
  address: 192.168.1.3
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?useSSL=false
    username: root
    password: password